version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: myproject-postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d 
    restart: unless-stopped

volumes:
  pgdata:
